stages:
  - build
  - test
  - report

default:
  image:
    name: registry.gitlab.com/kicad/kicad-ci/source_containers/master/fedora:36
    entrypoint: ["/bin/sh", "-c"]

include:
  - local: '/.gitlab/templates.yml'
  - local: '/.gitlab/Fedora-Linux-CI.yml'
  - local: '/.gitlab/Ubuntu-20.04-CI.yml'
  - local: '/.gitlab/Windows-CI.yml'
  - local: '/.gitlab/coverity.yml'
  - local: '/.gitlab/linux-metadata-validate.yml'
  - local: '/.gitlab/doxygen.yml'
  - local: '/.gitlab/mr_formatting.yml'
